"""initial schema

Revision ID: 956f9c43fbb3
Revises: 
Create Date: 2026-09-06 18:53:15.594129+00:00
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '956f9c43fbb3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dead_letter',
    sa.Column('task', sa.String(length=128), nullable=False),
    sa.Column('args', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('replayed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dead_letter_task'), 'dead_letter', ['task'], unique=False)
    op.create_table('job_run',
    sa.Column('task', sa.String(length=128), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('args', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_job_run_status'), 'job_run', ['status'], unique=False)
    op.create_index(op.f('ix_job_run_task'), 'job_run', ['task'], unique=False)
    op.create_table('learner',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=True),
    sa.Column('cohort_id', sa.UUID(), nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learner_organization_id'), 'learner', ['organization_id'], unique=False)
    op.create_table('skill_catalog',
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('slug', sa.String(length=96), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('level_descriptors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('best_evidence', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('taxonomy_version', sa.String(length=16), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_catalog_slug'), 'skill_catalog', ['slug'], unique=True)
    op.create_table('career_goal',
    sa.Column('learner_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('target_role', sa.String(length=255), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('motivation', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learner.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_goal_learner_id'), 'career_goal', ['learner_id'], unique=False)
    op.create_table('learner_personal_data',
    sa.Column('learner_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('location', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('contact', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('education', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('experience', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('languages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('learning_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_of_truth', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learner.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('learner_id')
    )
    op.create_table('learner_profile',
    sa.Column('learner_id', sa.UUID(), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('profile_version', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stale_dimensions', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learner.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('learner_id')
    )
    op.create_index(op.f('ix_learner_profile_organization_id'), 'learner_profile', ['organization_id'], unique=False)
    op.create_table('learner_technical_skill',
    sa.Column('learner_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('declared_level', sa.SmallInteger(), nullable=True),
    sa.Column('assessed_level', sa.SmallInteger(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_card_ids', sa.ARRAY(sa.UUID()), nullable=False),
    sa.Column('last_evidence_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learner.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('learner_id', 'label', name='uq_tech_skill_learner_label')
    )
    op.create_index(op.f('ix_learner_technical_skill_learner_id'), 'learner_technical_skill', ['learner_id'], unique=False)
    op.create_table('raw_document',
    sa.Column('learner_id', sa.UUID(), nullable=True),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('extractor_version', sa.String(length=64), nullable=True),
    sa.Column('error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learner.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'content_sha256', name='uq_raw_document_content'),
    sa.UniqueConstraint('organization_id', 'source_type', 'external_id', name='uq_raw_document_external')
    )
    op.create_index(op.f('ix_raw_document_content_sha256'), 'raw_document', ['content_sha256'], unique=False)
    op.create_index(op.f('ix_raw_document_learner_id'), 'raw_document', ['learner_id'], unique=False)
    op.create_index(op.f('ix_raw_document_occurred_at'), 'raw_document', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_raw_document_organization_id'), 'raw_document', ['organization_id'], unique=False)
    op.create_index(op.f('ix_raw_document_source_type'), 'raw_document', ['source_type'], unique=False)
    op.create_index(op.f('ix_raw_document_status'), 'raw_document', ['status'], unique=False)
    op.create_table('skill_assessment',
    sa.Column('learner_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.SmallInteger(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_card_ids', sa.ARRAY(sa.UUID()), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('method', sa.String(length=32), nullable=False),
    sa.Column('synthesizer_version', sa.String(length=32), nullable=False),
    sa.Column('taxonomy_version', sa.String(length=16), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('superseded', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learner.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skill_catalog.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_assessment_learner_id'), 'skill_assessment', ['learner_id'], unique=False)
    op.create_index(op.f('ix_skill_assessment_organization_id'), 'skill_assessment', ['organization_id'], unique=False)
    op.create_index(op.f('ix_skill_assessment_superseded'), 'skill_assessment', ['superseded'], unique=False)
    op.create_table('learning_journey',
    sa.Column('learner_id', sa.UUID(), nullable=False),
    sa.Column('career_goal_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('progress', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('plan', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['career_goal_id'], ['career_goal.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['learner_id'], ['learner.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_journey_learner_id'), 'learning_journey', ['learner_id'], unique=False)
    op.create_table('memory_card',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('learner_id', sa.UUID(), nullable=False),
    sa.Column('source_document_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('card_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('evidence_quote', sa.Text(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('salience', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('superseded_by', sa.UUID(), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('vector_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extractor_version', sa.String(length=64), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=96), nullable=False),
    sa.Column('schema_version', sa.String(length=16), nullable=False),
    sa.Column('contributions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learner.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_document_id'], ['raw_document.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_card_card_type'), 'memory_card', ['card_type'], unique=False)
    op.create_index(op.f('ix_memory_card_extractor_version'), 'memory_card', ['extractor_version'], unique=False)
    op.create_index(op.f('ix_memory_card_learner_id'), 'memory_card', ['learner_id'], unique=False)
    op.create_index(op.f('ix_memory_card_observed_at'), 'memory_card', ['observed_at'], unique=False)
    op.create_index(op.f('ix_memory_card_organization_id'), 'memory_card', ['organization_id'], unique=False)
    op.create_index(op.f('ix_memory_card_source_document_id'), 'memory_card', ['source_document_id'], unique=False)
    op.create_index(op.f('ix_memory_card_source_type'), 'memory_card', ['source_type'], unique=False)
    op.create_index(op.f('ix_memory_card_status'), 'memory_card', ['status'], unique=False)
    op.create_index(op.f('ix_memory_card_vector_synced_at'), 'memory_card', ['vector_synced_at'], unique=False)
    op.create_table('card_contribution',
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('target', sa.String(length=32), nullable=False),
    sa.Column('key', sa.String(length=96), nullable=False),
    sa.Column('level_signal', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['memory_card.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('card_id', 'target', 'key')
    )
    op.create_index('ix_card_contribution_target_key', 'card_contribution', ['target', 'key'], unique=False)
    op.create_table('journey_step',
    sa.Column('journey_id', sa.UUID(), nullable=False),
    sa.Column('ord', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('evidence_card_ids', sa.ARRAY(sa.UUID()), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['journey_id'], ['learning_journey.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journey_step_journey_id'), 'journey_step', ['journey_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_journey_step_journey_id'), table_name='journey_step')
    op.drop_table('journey_step')
    op.drop_index('ix_card_contribution_target_key', table_name='card_contribution')
    op.drop_table('card_contribution')
    op.drop_index(op.f('ix_memory_card_vector_synced_at'), table_name='memory_card')
    op.drop_index(op.f('ix_memory_card_status'), table_name='memory_card')
    op.drop_index(op.f('ix_memory_card_source_type'), table_name='memory_card')
    op.drop_index(op.f('ix_memory_card_source_document_id'), table_name='memory_card')
    op.drop_index(op.f('ix_memory_card_organization_id'), table_name='memory_card')
    op.drop_index(op.f('ix_memory_card_observed_at'), table_name='memory_card')
    op.drop_index(op.f('ix_memory_card_learner_id'), table_name='memory_card')
    op.drop_index(op.f('ix_memory_card_extractor_version'), table_name='memory_card')
    op.drop_index(op.f('ix_memory_card_card_type'), table_name='memory_card')
    op.drop_table('memory_card')
    op.drop_index(op.f('ix_learning_journey_learner_id'), table_name='learning_journey')
    op.drop_table('learning_journey')
    op.drop_index(op.f('ix_skill_assessment_superseded'), table_name='skill_assessment')
    op.drop_index(op.f('ix_skill_assessment_organization_id'), table_name='skill_assessment')
    op.drop_index(op.f('ix_skill_assessment_learner_id'), table_name='skill_assessment')
    op.drop_table('skill_assessment')
    op.drop_index(op.f('ix_raw_document_status'), table_name='raw_document')
    op.drop_index(op.f('ix_raw_document_source_type'), table_name='raw_document')
    op.drop_index(op.f('ix_raw_document_organization_id'), table_name='raw_document')
    op.drop_index(op.f('ix_raw_document_occurred_at'), table_name='raw_document')
    op.drop_index(op.f('ix_raw_document_learner_id'), table_name='raw_document')
    op.drop_index(op.f('ix_raw_document_content_sha256'), table_name='raw_document')
    op.drop_table('raw_document')
    op.drop_index(op.f('ix_learner_technical_skill_learner_id'), table_name='learner_technical_skill')
    op.drop_table('learner_technical_skill')
    op.drop_index(op.f('ix_learner_profile_organization_id'), table_name='learner_profile')
    op.drop_table('learner_profile')
    op.drop_table('learner_personal_data')
    op.drop_index(op.f('ix_career_goal_learner_id'), table_name='career_goal')
    op.drop_table('career_goal')
    op.drop_index(op.f('ix_skill_catalog_slug'), table_name='skill_catalog')
    op.drop_table('skill_catalog')
    op.drop_index(op.f('ix_learner_organization_id'), table_name='learner')
    op.drop_table('learner')
    op.drop_index(op.f('ix_job_run_task'), table_name='job_run')
    op.drop_index(op.f('ix_job_run_status'), table_name='job_run')
    op.drop_table('job_run')
    op.drop_index(op.f('ix_dead_letter_task'), table_name='dead_letter')
    op.drop_table('dead_letter')
    # ### end Alembic commands ###
