"""Storage port. Swapping Supabase for S3/MinIO means one new adapter."""
from __future__ import annotations

from typing import Protocol


class ObjectStorage(Protocol):
    async def put(self, key: str, data: bytes, *, content_type: str | None = None) -> str: ...
    async def get(self, key: str) -> bytes: ...
    async def signed_url(self, key: str, *, expires_in: int = 300) -> str: ...
    async def signed_upload_url(self, key: str, *, expires_in: int = 3600) -> str: ...
    async def exists(self, key: str) -> bool: ...
    async def delete(self, key: str) -> None: ...
